version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=d4t4b1z*redmine'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: redmine:latest
    restart: always
    networks:
      - redmine
    volumes:
    #   - ./redmine-data:/usr/src/redmine/files
      - redmine-data:/usr/src/redmine/files
      - ./redmine-plugins:/usr/src/redmine/plugins
      - ./redmine-themes:/usr/src/redmine/public/themes
    ports:
      - 80:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=d4t4b1z*redmine'
      - 'REDMINE_PLUGINS_MIGRATE=true'
volumes:
  postgres-data:
    driver: local
  redmine-data:
    driver: local
networks:
  redmine:
    driver: bridge